use_frameworks!

target 'ZJNetworking_Example' do
  pod 'ZJNetworking', :path => '../'

  target 'ZJNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
